# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "composer" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    # Add assignees
    assignees:
      - "GaryJones"
    # Prefix all commit messages with "Composer"
    # include a list of updated dependencies
    commit-message:
      prefix: "Composer"
      include: "scope"
    # Specify labels for Composer pull requests
    labels:
      - "dependencies"
    # Bundle minor and patch updates into a single pull request.
    groups:
      composer-minor-and-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "GaryJones"
    # Prefix all commit messages with "Actions"
    # include a list of updated dependencies
    commit-message:
      prefix: "Actions"
      include: "scope"
    # Specify labels for GitHub Actions pull requests
    labels:
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "GaryJones"
    # Prefix all commit messages with "NPM"
    # include a list of updated dependencies
    commit-message:
      prefix: "NPM"
      include: "scope"
    # Specify labels for npm pull requests
    labels:
      - "dependencies"
