dist: bionic

services:
  - mysql

language: php

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 7.4
  - "nightly"

before_install:
  # Turn off Xdebug
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"

install: composer install --no-interaction

stages:
 - lint and code standards
 - test

jobs:
  allow_failures:
    # Allow failures for unstable builds.
    - php: "nightly"
  include:
    - stage: lint and code standards
      php: 7.4
      addons:
        apt:
          packages:
           - libxml2-utils # Needed for XML linting.
      before_script:
        - export XMLLINT_INDENT="	" # Tab character.
      script:
        # Validate the XML files.
        # @link http://xmlsoft.org/xmllint.html
        - xmllint --noout ./.phpcs.xml.dist
        - xmllint --noout --schema ./vendor/phpunit/phpunit/phpunit.xsd ./phpunit.xml.dist

        # Lint the PHP files against parse errors.
        - if find . -path ./vendor -prune -o -name "*.php" -exec php -l {} \; | grep "^[Parse error|Fatal error]"; then exit 1; fi

        # Check code standards
        - composer phpcs

    - stage: test
      env: WP_VERSION=latest WP_MULTISITE=1
      install:
        - composer install --no-interaction
        - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      before_script:
        # Re-enable Xdebug.
        - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{.disabled,}
        - if [[ ! $(php -m | grep -si xdebug) ]]; then echo "xdebug required for coverage"; exit 1; fi
      script:
        - vendor/bin/phpunit --testsuite unit
#        - vendor/bin/infection

        # WP integration tests don't yet run with PHPUnit 8, and PHPUnit 7 doesn't work with PHP 7.4
        - |
        - if [[ ${TRAVIS_PHP_VERSION:0:3} < "7.4" ]]; then
            vendor/bin/phpunit --testsuite integration
          fi

cache:
  directories:
    - $HOME/.composer/cache
