blank_issues_enabled: false
contact_links:
  - name: Support
    url: https://github.com/GaryJones/plugin-slug/blob/main/.github/SUPPORT.md
    about: See the support document for ways to get help with this plugin.
