# https://github.com/10up/action-wordpress-plugin-asset-update

# This Action commits any readme and WordPress.org-specific assets changes in your specified branch to the
# WordPress.org plugin repository if no other changes have been made since the last deployment to WordPress.org.
# This is useful for updating things like screenshots or Tested up to separately from functional changes, provided
# your Git branching methodology avoids changing anything else in the specified branch between functional releases.

name: Plugin asset/readme update
on:
  push:
    branches:
      - master
jobs:
  master:
    name: Update plugin and assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: WordPress.org plugin asset/readme update
        uses: 10up/action-wordpress-plugin-asset-update@master
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }} # Set in repo -> Settings -> Secrets
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }} # Set in repo -> Settings -> Secrets
          README_NAME: README.md
        continue-on-error: true # Remove for real plugin
