# https://github.com/10up/action-wordpress-plugin-deploy

# This Action commits the contents of your Git tag to the WordPress.org plugin repository using the same tag name.
# It can exclude files as defined in either .distignore or .gitattributes, and moves anything from a .wordpress-org
# subdirectory to the top-level assets directory in Subversion (plugin banners, icons, and screenshots).

name: Deploy to WordPress.org
on:
  release:
    types: [ released ]
  # Allow manual triggering of the workflow.
  workflow_dispatch:
jobs:
  release:
    name: New release to WordPress.org
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Push to WordPress.org
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SLUG: my-super-cool-plugin # Change this
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        continue-on-error: true # Remove for real plugin
